# Generated by Django 5.2.1 on 2025-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('interview', 'Interview'), ('final_round', 'Final Round'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
