# Generated by Django 5.2.1 on 2025-07-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0004_alter_employerprofile_email'),
        ('job_seeker', '0005_remove_jobseekerprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('work_mode', models.CharField(choices=[('on-site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on-site', max_length=10)),
                ('skills', models.ManyToManyField(related_name='jobs', to='job_seeker.skill')),
            ],
        ),
    ]
